version: '3.7'

networks:
  default:
    driver: bridge

services:

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todo
      - MYSQL_USER=todo
      - MYSQL_PASSWORD=todo
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - default
